spring:
  datasource:
    username: djzxcs
    password: abc@1234
    url: jdbc:mysql://10.10.8.101:3306/djzx_cs

  datasourceSlave:
    username: djzxcs
    password: abc@1234
    url: jdbc:mysql://10.10.4.11:3306/djzx_cs


mybatis:
  type-aliases-package: com.lvlivejp.masterslavedb.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
